# 01 — NumPy Fundamentals

**Topics covered:**
1. Creating arrays
2. Array attributes & dtypes
3. Indexing & slicing
4. Reshaping & stacking
5. Vectorised operations & broadcasting
6. Linear algebra
7. Random number generation
8. Practical mini-exercises

In [2]:
import numpy as np
print(f'NumPy version: {np.__version__}')

NumPy version: 1.26.4


## 1. Creating Arrays

In [3]:
# From Python lists
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print('1-D:', a1)
print('2-D:\n', a2)

1-D: [1 2 3 4 5]
2-D:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Built-in factory functions
print(np.zeros((3, 4)))
print(np.ones((2, 3)))
print(np.eye(4))
print(np.arange(0, 20, 2))        # [0, 2, 4, ... 18]
print(np.linspace(0, 1, 6))       # 6 evenly-spaced points in [0, 1]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.2 0.4 0.6 0.8 1. ]


## 2. Array Attributes

In [5]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
print('shape :', x.shape)
print('ndim  :', x.ndim)
print('size  :', x.size)
print('dtype :', x.dtype)
print('nbytes:', x.nbytes)

shape : (2, 3)
ndim  : 2
size  : 6
dtype : float64
nbytes: 48


## 3. Indexing & Slicing

In [6]:
arr = np.arange(12).reshape(3, 4)
print(arr)
print('Row 0      :', arr[0])
print('Col 2      :', arr[:, 2])
print('Sub-matrix :\n', arr[0:2, 1:3])

# Boolean indexing
print('Values > 6 :', arr[arr > 6])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Row 0      : [0 1 2 3]
Col 2      : [ 2  6 10]
Sub-matrix :
 [[1 2]
 [5 6]]
Values > 6 : [ 7  8  9 10 11]


## 4. Reshaping & Stacking

In [7]:
a = np.arange(6)
print('Original  :', a)
print('Reshaped  :\n', a.reshape(2, 3))
print('Flattened :', a.reshape(2, 3).ravel())

b = np.array([10, 20, 30])
c = np.array([40, 50, 60])
print('hstack :', np.hstack([b, c]))
print('vstack :\n', np.vstack([b, c]))

Original  : [0 1 2 3 4 5]
Reshaped  :
 [[0 1 2]
 [3 4 5]]
Flattened : [0 1 2 3 4 5]
hstack : [10 20 30 40 50 60]
vstack :
 [[10 20 30]
 [40 50 60]]


## 5. Vectorised Operations & Broadcasting

In [12]:
v = np.array([1., 2., 3., 4.])
print('v * 3       :', v * 3)
print('v ** 2      :', v ** 2)
print('sqrt(v)     :', np.sqrt(v))
print('sum         :', v.sum())
print('mean        :', v.mean())
print('std         :', v.std())

# Broadcasting example: add a column vector to each column of a matrix
mat = np.ones((3, 4))
col = np.array([[1], [2], [3]])   # shape (3, 1)
print('\nBroadcast add:\n', mat + col)

v * 3       : [ 3.  6.  9. 12.]
v ** 2      : [ 1.  4.  9. 16.]
sqrt(v)     : [1.         1.41421356 1.73205081 2.        ]
sum         : 10.0
mean        : 2.5
std         : 1.118033988749895

Broadcast add:
 [[2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


## 6. Linear Algebra

In [13]:
A = np.array([[2., 1.], [5., 3.]])
B = np.array([[1., 2.], [3., 4.]])

print('A @ B (matmul):\n', A @ B)
print('Determinant of A :', np.linalg.det(A))
print('Inverse of A:\n', np.linalg.inv(A))

# Eigenvalues / eigenvectors
vals, vecs = np.linalg.eig(A)
print('Eigenvalues :', vals)
print('Eigenvectors:\n', vecs)

A @ B (matmul):
 [[ 5.  8.]
 [14. 22.]]
Determinant of A : 1.0000000000000002
Inverse of A:
 [[ 3. -1.]
 [-5.  2.]]
Eigenvalues : [0.20871215 4.79128785]
Eigenvectors:
 [[-0.48744474 -0.33726692]
 [ 0.87315384 -0.94140906]]


## 7. Random Number Generation

In [20]:
rng = np.random.default_rng(seed=42)

# Distributions
uniform   = rng.uniform(0, 1, size=5)
normal    = rng.normal(loc=0, scale=1, size=5)
integers  = rng.integers(1, 100, size=10)

print('Uniform :', uniform)
print('Normal  :', normal)
print('Integers:', integers)

# Shuffle & choice
arr = np.arange(10)
rng.shuffle(arr)
print('Shuffled:', arr)
print('Choice  :', rng.choice(arr, size=3, replace=False))

Uniform : [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Normal  : [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
Integers: [50 37 19 92 78 64 40 82 54 44]
Shuffled: [6 9 1 5 4 0 8 7 3 2]
Choice  : [5 0 6]


## 8. Mini-Exercises

Try these yourself:

In [29]:
# Exercise 1: Create a 5x5 identity matrix and replace its diagonal with [1,2,3,4,5]
# Your code here
# Create a 5x5 identity matrix
matrix = np.eye(5)

np.fill_diagonal(matrix, [1,2,3,4,5])

print(matrix)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [45]:
# Exercise 2: Generate 1000 random samples from N(5, 2) and compute mean, std, min, max
# Your code here
samples = np.random.normal(loc=5, scale =2, size = 1000)
samples

# Compute statistics
mean = np.mean(samples)
std  = np.std(samples)
min_ = np.min(samples)
max_ = np.max(samples)
print(f"mean : {mean:.4f}")
print(f"std : {std:.4f}")
print(f"min : {min_:.4f}")
print(f"max : {max_:.4f}")


mean : 4.9736
std : 2.0522
min : -1.7200
max : 11.7077


In [46]:
# Exercise 3: Given a 6x6 matrix of integers, extract all values on the anti-diagonal
# Your code here
import numpy as np

# Create a 6x6 matrix of integers
matrix = np.arange(1, 37).reshape(6, 6)
print("Matrix:")
print(matrix)

# Extract anti-diagonal (top-right to bottom-left)
n = matrix.shape[0]
anti_diag = matrix[np.arange(n), np.arange(n-1, -1, -1)]

print(f"\nAnti-diagonal: {anti_diag}")


Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Anti-diagonal: [ 6 11 16 21 26 31]
